version: "2.4"

services:
  edge-node-red-unified:
    container_name: edge-node-red-unified
    build:
      context: ./edge-node-red-unified
      dockerfile: Dockerfile
      args:
        - NODE_RED_VERSION=2.1.3
    image: edge-node-red-unified:2.1.3
    restart: always
    #privileged: true
    cap_add:
      - SYS_ADMIN
      #- DAC_READ_SEARCH
      - ALL
    environment:
      - TZ=Europe/Rome
    ports:
      - "41880:1880"
      - "44840:44840"
    networks:
      - proxy-redirect
    volumes:
      - edge-node-red-data:/data/
      - /tmp/siemens/automation:/tempcontainer/
      - /media/simatic:/media/simatic:ro,slave
    mem_limit: 768m

volumes:
  edge-node-red-data:
    name: edge-node-red-data

networks:
  proxy-redirect:
    name: proxy-redirect
